#requires -Version 7.0
<#
.SYNOPSIS
  Render ludi-agent-kit into a pi agent directory layout. DRY-RUN BY DEFAULT.

.DESCRIPTION
  Composes the generated AGENTS.md, plans Junctions for skills/agents/extensions, and
  renders an MCP proposal. Without -Apply nothing outside the repository is written:
  all generated content goes to adapters/pi/out/ (gitignored) and a plan is printed.

  With -Apply, only these operations are performed against -AgentDir:
    * write AGENTS.md          (existing file is backed up to <AgentDir>/ludi-agent-kit/backup-*/)
    * create Junctions          skills/<name>, agents/ludi-agent-kit, extensions/ludi-agent-kit, extensions/ludi-orchestrator
  settings.json, auth.json, models.json, mcp.json, sessions are NEVER modified.
  Existing entries that are not Junctions pointing at this kit stop the run unless
  -BackupConflicts is given (they are moved into the backup directory, never deleted).
#>
[CmdletBinding()]
param(
    [string]$AgentDir,
    [switch]$Apply,
    [switch]$BackupConflicts
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if (-not $IsWindows) { throw 'sync-pi.ps1 targets native Windows (Junctions).' }

$kit = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..'))
if (-not $AgentDir) { $AgentDir = if ($env:PI_CODING_AGENT_DIR) { $env:PI_CODING_AGENT_DIR } else { Join-Path $env:USERPROFILE '.pi/agent' } }
$AgentDir = [IO.Path]::GetFullPath($AgentDir)
$out = Join-Path $PSScriptRoot 'out'
New-Item -ItemType Directory -Path $out -Force | Out-Null

# ---- validate kit configs through the shared loader (fail fast, no user writes) ----
& node (Join-Path $kit 'scripts/validate.mjs') | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'Kit validation failed; fix routing/context-pack/agents before syncing.' }

# ---- compose AGENTS.md ----
$common = (Get-Content (Join-Path $kit 'rules/common.md') -Raw).Trim()
$loop = (Get-Content (Join-Path $kit 'rules/loop-prevention.md') -Raw).Trim()
$agentsText = "<!-- Generated by ludi-agent-kit/adapters/pi/sync-pi.ps1; do not edit. Sources: rules/common.md, rules/loop-prevention.md -->`n$common`n`n$loop`n"
[IO.File]::WriteAllText((Join-Path $out 'AGENTS.md'), $agentsText, [Text.UTF8Encoding]::new($false))

# ---- plan links ----
$links = [ordered]@{}
foreach ($skill in Get-ChildItem (Join-Path $kit 'skills') -Directory) {
    if (Test-Path (Join-Path $skill.FullName 'SKILL.md')) { $links["skills/$($skill.Name)"] = $skill.FullName }
}
$links['agents/ludi-agent-kit'] = Join-Path $kit 'agents'
$links['extensions/ludi-agent-kit'] = Join-Path $kit 'adapters/pi/loop-guard'
$links['extensions/ludi-orchestrator'] = Join-Path $kit 'adapters/pi/orchestrator-ext'

# ---- render MCP proposal from the neutral catalog ----
$catalog = Get-Content (Join-Path $kit 'mcp/servers.json') -Raw | ConvertFrom-Json
$mcp = [ordered]@{ mcpServers = [ordered]@{} }
foreach ($p in $catalog.servers.PSObject.Properties) {
    $s = $p.Value
    if (-not $s.enabled) { continue }
    $entry = [ordered]@{}
    if ($s.transport -eq 'http') { $entry.url = $s.url } else { $entry.command = $s.command; if ($s.args) { $entry.args = @($s.args) } }
    if ($s.authEnv) { $entry.headers = @{ Authorization = "Bearer `${$($s.authEnv)}" } }
    $mcp.mcpServers[$p.Name] = $entry
}
($mcp | ConvertTo-Json -Depth 10) | Set-Content (Join-Path $out 'mcp.proposal.json') -Encoding utf8NoBOM

# ---- models: resolve every capability through routing + pi model map (report only) ----
# resolve-capabilities writes out/capabilities.resolved.json and out/settings.proposal.json (models.json + models.local.json)
$resolved = & node (Join-Path $kit 'scripts/resolve-capabilities.mjs') --live-settings (Join-Path $AgentDir 'settings.json')
if ($LASTEXITCODE -ne 0) { throw 'Capability resolution failed; check adapters/pi/models*.json.' }

# ---- diff plan against the live agent dir (read-only) ----
$plan = [Collections.Generic.List[object]]::new()
foreach ($rel in $links.Keys) {
    $dest = Join-Path $AgentDir $rel
    $existing = Get-Item -LiteralPath $dest -Force -ErrorAction SilentlyContinue
    $state = if (-not $existing) { 'create' }
        elseif ($existing.LinkType -eq 'Junction' -and [IO.Path]::GetFullPath($existing.Target) -eq [IO.Path]::GetFullPath($links[$rel])) { 'ok' }
        elseif ($existing.LinkType -eq 'Junction') { "conflict-junction->$($existing.Target)" }
        else { 'conflict-existing' }
    $plan.Add([pscustomobject]@{ entry = $rel; target = $links[$rel]; state = $state })
}
$agentsPath = Join-Path $AgentDir 'AGENTS.md'
$agentsState = if (-not (Test-Path -LiteralPath $agentsPath)) { 'create' }
    elseif ((Get-Content -LiteralPath $agentsPath -Raw) -ceq $agentsText) { 'ok' }
    elseif ((Get-Content -LiteralPath $agentsPath -Raw) -match '^<!-- Generated by ludi-agent-kit') { 'update-managed' }
    else { 'conflict-existing' }
$plan.Add([pscustomobject]@{ entry = 'AGENTS.md'; target = (Join-Path $out 'AGENTS.md'); state = $agentsState })

$settingsPath = Join-Path $AgentDir 'settings.json'
$settingsNotes = @()
if (Test-Path -LiteralPath $settingsPath) {
    $live = Get-Content -LiteralPath $settingsPath -Raw | ConvertFrom-Json -AsHashtable
    $tpl = Get-Content (Join-Path $PSScriptRoot 'settings.template.json') -Raw | ConvertFrom-Json -AsHashtable
    foreach ($key in $tpl.Keys) {
        if ($key -like '$*') { continue }
        $liveVal = if ($live.ContainsKey($key)) { $live[$key] | ConvertTo-Json -Compress } else { '<absent>' }
        $tplVal = $tpl[$key] | ConvertTo-Json -Compress
        if ($liveVal -cne $tplVal) { $settingsNotes += "settings.$key live=$liveVal template=$tplVal (not changed; user-owned)" }
    }
}

$report = [ordered]@{
    mode = if ($Apply) { 'apply' } else { 'dry-run' }
    agentDir = $AgentDir
    outDir = $out
    plan = $plan
    settingsDifferences = $settingsNotes
    neverTouched = @('settings.json', 'auth.json', 'models.json', 'models-store.json', 'mcp.json', 'sessions/')
}
$report | ConvertTo-Json -Depth 6 | Set-Content (Join-Path $out 'plan.json') -Encoding utf8NoBOM
$plan | Format-Table -AutoSize | Out-String | Write-Output
if ($settingsNotes) { $settingsNotes | ForEach-Object { Write-Output "note: $_" } }

if (-not $Apply) { Write-Output "DRY-RUN complete. Generated files in $out. Re-run with -Apply to create Junctions/AGENTS.md in $AgentDir."; return }

# ---- apply (bounded) ----
$conflicts = @($plan | Where-Object { $_.state -like 'conflict-*' })
if ($conflicts.Count -and -not $BackupConflicts) { throw "Conflicts present; review plan and re-run with -BackupConflicts to move them into a backup directory:`n$($conflicts | Out-String)" }
$backup = Join-Path $AgentDir ('ludi-agent-kit/backup-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
foreach ($entry in $plan) {
    if ($entry.state -eq 'ok') { continue }
    $dest = Join-Path $AgentDir $entry.entry
    New-Item -ItemType Directory -Path (Split-Path $dest -Parent) -Force | Out-Null
    if ($entry.state -like 'conflict-*' -or $entry.state -eq 'update-managed') {
        New-Item -ItemType Directory -Path $backup -Force | Out-Null
        $bk = Join-Path $backup ($entry.entry -replace '[\\/]', '__')
        $item = Get-Item -LiteralPath $dest -Force
        if ($item.LinkType -eq 'Junction') { $item.Delete() }  # removes the link only, never its target
        else { Move-Item -LiteralPath $dest -Destination $bk }
        Write-Output "backed up $($entry.entry) -> $bk"
    }
    if ($entry.entry -eq 'AGENTS.md') { [IO.File]::WriteAllText($dest, $agentsText, [Text.UTF8Encoding]::new($false)) }
    else { New-Item -ItemType Junction -Path $dest -Target $entry.target | Out-Null }
    Write-Output "applied $($entry.entry)"
}
Write-Output "APPLY complete. Restart pi or /reload."

