#requires -Version 7.0
# Exercises adapters/pi/sync-pi.ps1 against an isolated temporary agent dir.
# Dry-run must write nothing to the target; -Apply must create only the planned entries and never touch settings/auth.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$kit = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$root = Join-Path ([IO.Path]::GetTempPath()) ('ludi-kit-sync-' + [guid]::NewGuid().ToString('N').Substring(0, 8))
$agent = Join-Path $root 'agent'
New-Item -ItemType Directory -Path $agent | Out-Null
$settings = '{"defaultProvider":"fixture","defaultModel":"fixture-model","defaultTools":["read"]}'
[IO.File]::WriteAllText((Join-Path $agent 'settings.json'), $settings)
[IO.File]::WriteAllText((Join-Path $agent 'auth.json'), '{"fixture":"not-a-real-secret"}')
[IO.File]::WriteAllText((Join-Path $agent 'AGENTS.md'), '# user instructions')
$sync = Join-Path $kit 'adapters/pi/sync-pi.ps1'

# 1. dry-run: nothing changes in target
$before = Get-ChildItem $agent -Recurse -Force | Select-Object -ExpandProperty FullName | Sort-Object
& pwsh -NoProfile -File $sync -AgentDir $agent | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'dry-run failed' }
$after = Get-ChildItem $agent -Recurse -Force | Select-Object -ExpandProperty FullName | Sort-Object
if (($before -join '|') -cne ($after -join '|')) { throw 'dry-run modified the agent directory' }
$plan = Get-Content (Join-Path $kit 'adapters/pi/out/plan.json') -Raw | ConvertFrom-Json
if ($plan.mode -ne 'dry-run') { throw 'plan mode should be dry-run' }
if (-not ($plan.plan | Where-Object { $_.entry -eq 'AGENTS.md' -and $_.state -eq 'conflict-existing' })) { throw 'existing AGENTS.md should be reported as conflict' }
if (-not ($plan.plan | Where-Object { $_.entry -eq 'skills/visual-verification' -and $_.state -eq 'create' })) { throw 'skill link should be planned' }
if (-not (Test-Path (Join-Path $kit 'adapters/pi/out/AGENTS.md'))) { throw 'generated AGENTS.md missing' }

# 2. apply without -BackupConflicts must refuse and change nothing
$failed = $false
try { & pwsh -NoProfile -File $sync -AgentDir $agent -Apply 2>$null | Out-Null; if ($LASTEXITCODE -ne 0) { $failed = $true } } catch { $failed = $true }
if (-not $failed) { throw 'apply with conflicts should fail' }
if ((Get-Content (Join-Path $agent 'AGENTS.md') -Raw) -cne '# user instructions') { throw 'conflicting AGENTS.md was modified' }

# 3. apply with -BackupConflicts: junctions + AGENTS, backup retained, settings/auth untouched
& pwsh -NoProfile -File $sync -AgentDir $agent -Apply -BackupConflicts | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'apply failed' }
foreach ($rel in 'skills/visual-verification', 'skills/project-management', 'skills/pi-workflow', 'agents/ludi-agent-kit', 'extensions/ludi-agent-kit', 'extensions/ludi-orchestrator') {
    $item = Get-Item -LiteralPath (Join-Path $agent $rel) -Force
    if ($item.LinkType -ne 'Junction') { throw "$rel is not a Junction" }
}
if ((Get-Content (Join-Path $agent 'AGENTS.md') -Raw) -notmatch '^<!-- Generated by ludi-agent-kit') { throw 'AGENTS.md not generated' }
$backups = @(Get-ChildItem (Join-Path $agent 'ludi-agent-kit') -Directory -Filter 'backup-*')
if ($backups.Count -ne 1 -or -not (Test-Path (Join-Path $backups[0].FullName 'AGENTS.md'))) { throw 'AGENTS.md backup missing' }
if ([IO.File]::ReadAllText((Join-Path $agent 'settings.json')) -cne $settings) { throw 'settings.json modified' }
if ([IO.File]::ReadAllText((Join-Path $agent 'auth.json')) -cne '{"fixture":"not-a-real-secret"}') { throw 'auth.json modified' }

# 4. repeat apply is a no-op
& pwsh -NoProfile -File $sync -AgentDir $agent -Apply | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'repeat apply failed' }
$plan = Get-Content (Join-Path $kit 'adapters/pi/out/plan.json') -Raw | ConvertFrom-Json
if ($plan.plan | Where-Object { $_.state -ne 'ok' }) { throw 'repeat apply should report all ok' }

# cleanup: remove junctions (links only) then fixture
foreach ($j in Get-ChildItem $agent -Recurse -Force -Attributes ReparsePoint) { $j.Delete() }
Remove-Item $root -Recurse -Force
Write-Output 'PASS: sync-pi dry-run writes nothing; apply is bounded, backed up and idempotent; settings/auth untouched'
